spring:
  application:
    name: hhplus
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true  # 테이블 만든뒤 data.sql 실행
    hibernate:
      ddl-auto: create
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
  # 여기에 추가
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql # 데이터 파일 위치
      encoding: UTF-8
---
spring.config.activate.on-profile: local, test

# H2 Database
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study-spring
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
